name: Lint, Test, and Document Helm Charts

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate values.yaml against values.schema.json
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm lint ./challenge-2/my-web-server

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.17.0  # specify the version of kind

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}

      - name: Install helm-docs
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.6.0/helm-docs_1.6.0_Linux_x86_64.tar.gz
          tar -xzvf helm-docs_1.6.0_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/bin

      - name: Generate Helm Chart Documentation
        if: steps.list-changed.outputs.changed == 'true'
        run: helm-docs

      - name: Commit and push documentation
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./challenge-2/my-web-server/README.md
          git commit -m "Update Helm chart documentation"
          git push origin ${{ github.ref }}
