name: Terraform Checks

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./challenge-3

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./challenge-3

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./challenge-3

      - name: Set up tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Initialize tflint
        run: tflint --init
        working-directory: ./challenge-3

      - name: Run tflint
        run: tflint | tee tflint_output.txt
        working-directory: ./challenge-3
        continue-on-error: true

      - name: Upload tflint output
        uses: actions/upload-artifact@v3
        with:
          name: tflint-output
          path: ./challenge-3/tflint_output.txt

      - name: Set up tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec . | tee tfsec_output.txt
        working-directory: ./challenge-3

      - name: Upload tfsec output
        uses: actions/upload-artifact@v3
        with:
          name: tfsec-output
          path: ./challenge-3/tfsec_output.txt
